// Maps a listings.country value (see src/config/countries.js) to the ISO3166-1
// alpha-3 code used as each country's class in public/world-map.svg, so the map's
// clickable regions can look up attorneys by the same country string we store.
const COUNTRY_ISO3 = {
  'United States': 'USA',
  Canada: 'CAN',
  'United Kingdom': 'GBR',
  Australia: 'AUS',
  Ireland: 'IRL',
  Afghanistan: 'AFG', Albania: 'ALB', Algeria: 'DZA', Andorra: 'AND', Angola: 'AGO',
  Argentina: 'ARG', Armenia: 'ARM', Austria: 'AUT', Azerbaijan: 'AZE', Bahamas: 'BHS',
  Bahrain: 'BHR', Bangladesh: 'BGD', Barbados: 'BRB', Belarus: 'BLR', Belgium: 'BEL',
  Belize: 'BLZ', Benin: 'BEN', Bhutan: 'BTN', Bolivia: 'BOL', 'Bosnia and Herzegovina': 'BIH',
  Botswana: 'BWA', Brazil: 'BRA', Brunei: 'BRN', Bulgaria: 'BGR', 'Burkina Faso': 'BFA',
  Burundi: 'BDI', 'Cabo Verde': 'CPV', Cambodia: 'KHM', Cameroon: 'CMR',
  'Central African Republic': 'CAF', Chad: 'TCD', Chile: 'CHL', China: 'CHN', Colombia: 'COL',
  Comoros: 'COM', Congo: 'COG', 'Costa Rica': 'CRI', Croatia: 'HRV', Cuba: 'CUB',
  Cyprus: 'CYP', Czechia: 'CZE', 'Democratic Republic of the Congo': 'COD', Denmark: 'DNK',
  Djibouti: 'DJI', Dominica: 'DMA', 'Dominican Republic': 'DOM', Ecuador: 'ECU', Egypt: 'EGY',
  'El Salvador': 'SLV', 'Equatorial Guinea': 'GNQ', Eritrea: 'ERI', Estonia: 'EST',
  Eswatini: 'SWZ', Ethiopia: 'ETH', Fiji: 'FJI', Finland: 'FIN', France: 'FRA', Gabon: 'GAB',
  Gambia: 'GMB', Georgia: 'GEO', Germany: 'DEU', Ghana: 'GHA', Greece: 'GRC', Grenada: 'GRD',
  Guatemala: 'GTM', Guinea: 'GIN', 'Guinea-Bissau': 'GNB', Guyana: 'GUY', Haiti: 'HTI',
  Honduras: 'HND', Hungary: 'HUN', Iceland: 'ISL', India: 'IND', Indonesia: 'IDN',
  Iran: 'IRN', Iraq: 'IRQ', Israel: 'ISR', Italy: 'ITA', Jamaica: 'JAM', Japan: 'JPN',
  Jordan: 'JOR', Kazakhstan: 'KAZ', Kenya: 'KEN', Kiribati: 'KIR', Kosovo: 'KOS',
  Kuwait: 'KWT', Kyrgyzstan: 'KGZ', Laos: 'LAO', Latvia: 'LVA', Lebanon: 'LBN',
  Lesotho: 'LSO', Liberia: 'LBR', Libya: 'LBY', Liechtenstein: 'LIE', Lithuania: 'LTU',
  Luxembourg: 'LUX', Madagascar: 'MDG', Malawi: 'MWI', Malaysia: 'MYS', Maldives: 'MDV',
  Mali: 'MLI', Malta: 'MLT', 'Marshall Islands': 'MHL', Mauritania: 'MRT', Mauritius: 'MUS',
  Mexico: 'MEX', Micronesia: 'FSM', Moldova: 'MDA', Monaco: 'MCO', Mongolia: 'MNG',
  Montenegro: 'MNE', Morocco: 'MAR', Mozambique: 'MOZ', Myanmar: 'MMR', Namibia: 'NAM',
  Nauru: 'NRU', Nepal: 'NPL', Netherlands: 'NLD', 'New Zealand': 'NZL', Nicaragua: 'NIC',
  Niger: 'NER', Nigeria: 'NGA', 'North Korea': 'PRK', 'North Macedonia': 'MKD', Norway: 'NOR',
  Oman: 'OMN', Pakistan: 'PAK', Palau: 'PLW', Palestine: 'PSE', Panama: 'PAN',
  'Papua New Guinea': 'PNG', Paraguay: 'PRY', Peru: 'PER', Philippines: 'PHL', Poland: 'POL',
  Portugal: 'PRT', Qatar: 'QAT', Romania: 'ROU', Russia: 'RUS', Rwanda: 'RWA',
  'Saint Kitts and Nevis': 'KNA', 'Saint Lucia': 'LCA', 'Saint Vincent and the Grenadines': 'VCT',
  Samoa: 'WSM', 'San Marino': 'SMR', 'Sao Tome and Principe': 'STP', 'Saudi Arabia': 'SAU',
  Senegal: 'SEN', Serbia: 'SRB', Seychelles: 'SYC', 'Sierra Leone': 'SLE', Singapore: 'SGP',
  Slovakia: 'SVK', Slovenia: 'SVN', 'Solomon Islands': 'SLB', Somalia: 'SOM',
  'South Africa': 'ZAF', 'South Korea': 'KOR', 'South Sudan': 'SSD', Spain: 'ESP',
  'Sri Lanka': 'LKA', Sudan: 'SDN', Suriname: 'SUR', Sweden: 'SWE', Switzerland: 'CHE',
  Syria: 'SYR', Taiwan: 'TWN', Tajikistan: 'TJK', Tanzania: 'TZA', Thailand: 'THA',
  'Timor-Leste': 'TLS', Togo: 'TGO', Tonga: 'TON', 'Trinidad and Tobago': 'TTO',
  Tunisia: 'TUN', Turkey: 'TUR', Turkmenistan: 'TKM', Uganda: 'UGA', Ukraine: 'UKR',
  'United Arab Emirates': 'ARE', Uruguay: 'URY', Uzbekistan: 'UZB', Vanuatu: 'VUT',
  'Vatican City': 'VAT', Venezuela: 'VEN', Vietnam: 'VNM', Yemen: 'YEM', Zambia: 'ZMB',
  Zimbabwe: 'ZWE',
};

module.exports = { COUNTRY_ISO3 };
